In [1]:
import tensorflow as tf

In [2]:
# Data를 행렬로 사용
x_data = [[73. , 80., 75.], [93. , 88., 93.], [89. , 91., 90.], 
          [96. , 98., 100.], [73. , 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [6]:
# X, Y Data에 대한 input 설정과 Shape 설정
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [8]:
# W, b 변수 생성 , W 의 shape 생성에 유의
W = tf.Variable(tf.random_normal([3, 1]), name = "weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")

In [9]:
# 행렬 계산 식 H(x) = XW + b
hypo = tf.matmul(X, W) + b

In [10]:
cost = tf.reduce_mean(tf.square(hypo - Y))

In [11]:
# Cost 최소화
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [12]:
# Learning 준비 
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [16]:
# 학습 구간
for step in range(2001) :
    cost_val, hy_val, _ = sess.run(
        [cost, hypo, train], feed_dict={X:x_data, Y:y_data}
    )
    if step % 10 == 0 :
        print(step, "\nCost : ", cost_val, "\nPrediction : \n", hy_val)

0 
Cost :  2.3646624 
Prediction : 
 [[149.16547]
 [186.00829]
 [179.82164]
 [197.62946]
 [141.70819]]
10 
Cost :  2.3600593 
Prediction : 
 [[149.16904]
 [186.00589]
 [179.8228 ]
 [197.62973]
 [141.70554]]
20 
Cost :  2.3555048 
Prediction : 
 [[149.17258]
 [186.00351]
 [179.82397]
 [197.63   ]
 [141.7029 ]]
30 
Cost :  2.350955 
Prediction : 
 [[149.17612]
 [186.00113]
 [179.82512]
 [197.63026]
 [141.70024]]
40 
Cost :  2.3464272 
Prediction : 
 [[149.17966]
 [185.99876]
 [179.82628]
 [197.63054]
 [141.69762]]
50 
Cost :  2.3419123 
Prediction : 
 [[149.1832 ]
 [185.99641]
 [179.82744]
 [197.63081]
 [141.69502]]
60 
Cost :  2.3374171 
Prediction : 
 [[149.18672]
 [185.99406]
 [179.8286 ]
 [197.63107]
 [141.69241]]
70 
Cost :  2.3329556 
Prediction : 
 [[149.19022]
 [185.9917 ]
 [179.82971]
 [197.63132]
 [141.68979]]
80 
Cost :  2.3285122 
Prediction : 
 [[149.19373]
 [185.98936]
 [179.83087]
 [197.63159]
 [141.6872 ]]
90 
Cost :  2.3240926 
Prediction : 
 [[149.19722]
 [185.98703]
 [

1160 
Cost :  1.9499117 
Prediction : 
 [[149.52444]
 [185.76877]
 [179.94   ]
 [197.65007]
 [141.44878]]
1170 
Cost :  1.9471842 
Prediction : 
 [[149.52708]
 [185.76697]
 [179.94084]
 [197.65013]
 [141.44688]]
1180 
Cost :  1.9444565 
Prediction : 
 [[149.52977]
 [185.76521]
 [179.94176]
 [197.65025]
 [141.44505]]
1190 
Cost :  1.9417394 
Prediction : 
 [[149.53242]
 [185.76347]
 [179.94264]
 [197.65033]
 [141.44322]]
1200 
Cost :  1.9390227 
Prediction : 
 [[149.53508]
 [185.7617 ]
 [179.94353]
 [197.6504 ]
 [141.44138]]
1210 
Cost :  1.9363558 
Prediction : 
 [[149.53769]
 [185.75992]
 [179.94438]
 [197.65048]
 [141.43951]]
1220 
Cost :  1.9336745 
Prediction : 
 [[149.54033]
 [185.75818]
 [179.94527]
 [197.65057]
 [141.43771]]
1230 
Cost :  1.931011 
Prediction : 
 [[149.54297]
 [185.75647]
 [179.94617]
 [197.65067]
 [141.4359 ]]
1240 
Cost :  1.9283634 
Prediction : 
 [[149.54558]
 [185.75471]
 [179.94702]
 [197.65074]
 [141.43407]]
1250 
Cost :  1.9257189 
Prediction : 
 [[149.5