In [1]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

In [2]:
# Normalize를 적용할 함수 시스템 
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [3]:
# Data 간의 큰 차이 때문에 결과의 오류가 발생하는 Data
xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

In [4]:
# 일반적으로 normalize를 적용하는 법, print를 통해 확인
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [5]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [7]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
hypothesis = tf.matmul(X, W) + b

In [9]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

In [10]:
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.46094203 
Prediction:
 [[-0.38276333]
 [ 1.5079312 ]
 [ 0.62377155]
 [-0.31488976]
 [ 0.05969322]
 [ 0.12003481]
 [-0.20971227]
 [ 0.57274306]]
1 Cost:  0.46093428 
Prediction:
 [[-0.38274616]
 [ 1.5079434 ]
 [ 0.6237826 ]
 [-0.31488022]
 [ 0.05970412]
 [ 0.12004513]
 [-0.20970592]
 [ 0.57274777]]
2 Cost:  0.46092662 
Prediction:
 [[-0.382729  ]
 [ 1.5079557 ]
 [ 0.6237935 ]
 [-0.31487072]
 [ 0.05971503]
 [ 0.12005544]
 [-0.20969963]
 [ 0.5727525 ]]
3 Cost:  0.4609189 
Prediction:
 [[-0.38271186]
 [ 1.5079677 ]
 [ 0.6238046 ]
 [-0.31486118]
 [ 0.05972588]
 [ 0.12006581]
 [-0.20969331]
 [ 0.5727572 ]]
4 Cost:  0.46091115 
Prediction:
 [[-0.38269472]
 [ 1.5079799 ]
 [ 0.62381554]
 [-0.31485164]
 [ 0.05973685]
 [ 0.12007618]
 [-0.209687  ]
 [ 0.5727619 ]]
5 Cost:  0.46090358 
Prediction:
 [[-0.38267756]
 [ 1.5079925 ]
 [ 0.62382644]
 [-0.31484213]
 [ 0.0597477 ]
 [ 0.12008649]
 [-0.2096807 ]
 [ 0.5727665 ]]
6 Cost:  0.46089584 
Prediction:
 [[-0.3826604 ]
 [ 1.5080045 ]
 [ 0.62