In [1]:
import tensorflow as tf

In [2]:
# for reproducibility
tf.set_random_seed(777)  

In [3]:
# Training Data 
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [4]:
# 마지막에 Test 용도로 사용할 Data
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [6]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [7]:
# SoftMax 적용
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [8]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

In [10]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [11]:
# 예측 결과값은 argmax를 이용하여 확인
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [12]:
# Learning 시작
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        # optimizer를 구할 때는 Test가 아닌 Training Data를 이용
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    
    # 에측, 정확도 확인에는 Test Data를 이용
    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.057414 [[-0.18843445  0.7173936   1.8718327 ]
 [-0.17902634 -0.30106387  0.24334279]
 [ 0.65033406  0.14627561  0.02859405]]
1 1.6560327 [[-0.17734164  0.74743676  1.8306967 ]
 [-0.07619639 -0.1487237  -0.01182732]
 [ 0.74223053  0.3076238  -0.22465065]]
2 0.8860614 [[-0.2000688   0.75083894  1.8500217 ]
 [-0.15853688 -0.10908215  0.03087161]
 [ 0.652716    0.35674465 -0.18425696]]
3 0.82901466 [[-0.19757472  0.7342307   1.8641359 ]
 [-0.10714342 -0.17746072  0.04785671]
 [ 0.69783884  0.29567206 -0.16830723]]
4 0.8124584 [[-0.21196702  0.73973733  1.8730215 ]
 [-0.14729209 -0.13242668  0.04297135]
 [ 0.64993125  0.3475684  -0.17229597]]
5 0.7977575 [[-0.21148     0.7289606   1.8833112 ]
 [-0.10776377 -0.17166892  0.04268526]
 [ 0.6832381   0.31429777 -0.17233217]]
6 0.78944564 [[-0.22250001  0.73116624  1.8921255 ]
 [-0.1308536  -0.14343755  0.0375437 ]
 [ 0.65324897  0.34858194 -0.17662722]]
7 0.7823883 [[-0.2242011   0.72289366  1.9020991 ]
 [-0.1039231  -0.16959266  0.03676832]

137 0.58651173 [[-0.8104854   0.47847506  2.732803  ]
 [ 0.04988777 -0.13657968 -0.15005521]
 [ 0.7343677   0.4433787  -0.35254252]]
138 0.5857702 [[-0.8142389   0.477719    2.7373126 ]
 [ 0.05019446 -0.13619451 -0.15074706]
 [ 0.7355606   0.44347832 -0.353835  ]]
139 0.58503306 [[-0.81798553  0.47697335  2.7418048 ]
 [ 0.05049674 -0.13581175 -0.15143211]
 [ 0.7367547   0.44357586 -0.35512662]]
140 0.5843007 [[-0.82172537  0.47623795  2.7462802 ]
 [ 0.05079485 -0.13543151 -0.15211043]
 [ 0.73795015  0.4436712  -0.3564174 ]]
141 0.58357275 [[-0.82545847  0.4755127   2.7507386 ]
 [ 0.05108871 -0.13505366 -0.15278213]
 [ 0.73914677  0.4437645  -0.3577073 ]]
142 0.58284914 [[-0.82918483  0.47479752  2.7551801 ]
 [ 0.05137853 -0.13467833 -0.15344729]
 [ 0.74034464  0.44385567 -0.3589963 ]]
143 0.5821301 [[-0.8329046   0.4740923   2.7596052 ]
 [ 0.05166421 -0.1343053  -0.15410598]
 [ 0.74154353  0.4439449  -0.3602844 ]]
144 0.58141524 [[-0.8366177   0.47339693  2.7640138 ]
 [ 0.05194601 -0.1